/**
 * Supplemental OpenAPI contract for routes not currently emitted by payload-oapi.
 * This includes custom endpoints and known auth/verification routes.
 */
export const customEndpointsOpenApi = {
  openapi: '3.0.3',
  info: {
    title: 'BS-Commerce Supplemental API Endpoints',
    version: '1.0.0',
    description: 'Supplemental contract for routes missing from autogenerated Payload OpenAPI output.',
  },
  paths: {
    '/api/users/login': {
      post: {
        summary: 'Payload auth login (email/username + password)',
        description:
          'Use this endpoint with `email` + `password` (or `username` + `password`). For identifier-based login use `/api/auth/login`.',
        requestBody: {
          required: true,
          content: {
            'application/json': {
              schema: {
                type: 'object',
                required: ['password'],
                properties: {
                  email: { type: 'string', format: 'email' },
                  username: { type: 'string' },
                  password: { type: 'string' },
                },
              },
            },
          },
        },
        responses: {
          200: { description: 'Authenticated.' },
          400: { description: 'Validation error.' },
          401: { description: 'Invalid credentials.' },
        },
      },
    },
    '/api/users/logout': {
      post: {
        summary: 'Payload auth logout',
        responses: {
          200: { description: 'Logged out.' },
          400: { description: 'Validation error.' },
          401: { description: 'Unauthorized.' },
        },
      },
    },
    '/api/users/me': {
      get: {
        summary: 'Current authenticated user profile',
        security: [{ bearerAuth: [] }],
        responses: {
          200: { description: 'Current user payload.' },
          401: { description: 'Unauthorized.' },
        },
      },
    },
    '/api/auth/login': {
      post: {
        summary: 'Login with email or phone identifier',
        requestBody: {
          required: true,
          content: {
            'application/json': {
              schema: {
                type: 'object',
                required: ['identifier', 'password'],
                properties: {
                  identifier: { type: 'string', description: 'Email or phone number.' },
                  password: { type: 'string' },
                },
              },
            },
          },
        },
        responses: {
          200: { description: 'Authenticated successfully.' },
          400: { description: 'Validation error.' },
          401: { description: 'Invalid credentials.' },
          403: { description: 'Verification gate blocked login.' },
        },
      },
    },
    '/api/guest/order-lookup': {
      post: {
        summary: 'Lookup guest order by reference and email/phone',
        responses: {
          200: { description: 'Order found.' },
          400: { description: 'Validation error.' },
          404: { description: 'Order not found.' },
        },
      },
    },
    '/api/checkout/process': {
      post: {
        summary: 'Process checkout payload into an order',
        description:
          'Guest identifiers follow AUTH_REQUIRED_IDENTIFIER (guestEmail / guestPhone). cashOnDelivery with shippingMethodIds skips hosted payment when every method has collect-on-delivery enabled; order keeps checkoutPaymentChannel=cash_on_delivery and paymentStatus unpaid. Optional `storeId` + `serviceArea` enable address-vs-store alignment checks controlled by ADDRESS_STORE_VALIDATION_MODE=off|warn|enforce.',
        responses: {
          201: {
            description:
              'Order created; JSON includes order.checkoutPaymentChannel (online|cash_on_delivery), paymentStatus snapshot, optional transaction id, optional paymentRedirectUrl for hosted gateway, and optional warnings/warningCodes/resolvedStoreId for address-store warn mode.',
          },
          400: { description: 'Invalid payload.' },
          401: { description: 'Unauthorized when required.' },
          409: { description: 'Inventory or business-rule conflict.' },
          501: { description: 'Payment provider not implemented.' },
          503: { description: 'Hosted payment not configured.' },
        },
      },
    },
    '/api/payments/sslcommerz/ipn': {
      post: {
        summary: 'SSL Commerz IPN webhook',
        description:
          'SSL Commerz POSTs form-urlencoded transaction fields. Server validates `val_id` with SSL, then marks the matching transaction succeeded and the order paid when validation succeeds.',
        responses: {
          200: { description: 'Acknowledged (always 200 for SSL compatibility).' },
        },
      },
    },
    '/api/payments/sslcommerz/sync-paid': {
      get: {
        summary: 'SSL Commerz success-page reconciliation',
        description:
          'Browser-callable alternative when IPN cannot reach the backend (e.g. localhost). Requires `val_id` from the gateway redirect query; optionally `tran_id`. Idempotent.',
        parameters: [
          { name: 'val_id', in: 'query', required: true, schema: { type: 'string' } },
          { name: 'tran_id', in: 'query', required: false, schema: { type: 'string' } },
        ],
        responses: {
          200: { description: 'Reconciliation attempted (check admin order if errors logged).' },
          400: { description: 'Missing val_id.' },
          500: { description: 'Server error.' },
        },
      },
    },
    '/api/storefront/store-products': {
      get: {
        summary: 'Storefront catalog — products with optional stock-location filter',
        description:
          'When `store` is set (stock location id), only products with available stock at that location are returned. Otherwise published products match filters as usual.',
        parameters: [
          { name: 'store', in: 'query', required: false, schema: { type: 'string' } },
          { name: 'page', in: 'query', required: false, schema: { type: 'integer', default: 1 } },
          { name: 'limit', in: 'query', required: false, schema: { type: 'integer', default: 12, maximum: 100 } },
          { name: 'sort', in: 'query', required: false, schema: { type: 'string', default: '-createdAt' } },
          { name: 'locale', in: 'query', required: false, schema: { type: 'string' } },
          { name: 'depth', in: 'query', required: false, schema: { type: 'integer', default: 1, maximum: 3 } },
          { name: 'category', in: 'query', required: false, schema: { type: 'string' } },
          { name: 'search', in: 'query', required: false, schema: { type: 'string' } },
          { name: 'featured', in: 'query', required: false, schema: { type: 'string', enum: ['true'] } },
          { name: 'tenant', in: 'query', required: false, schema: { type: 'string' } },
          { name: 'minPrice', in: 'query', required: false, schema: { type: 'number' } },
          { name: 'maxPrice', in: 'query', required: false, schema: { type: 'number' } },
        ],
        responses: {
          200: { description: 'Paginated products (same shape as Payload products find).' },
          500: { description: 'Server error.' },
        },
      },
    },
    '/api/dashboard-stats': {
      get: {
        summary: 'Role-scoped admin dashboard metrics',
        responses: {
          200: { description: 'Stats response for admin or vendor role.' },
          401: { description: 'Unauthorized.' },
          403: { description: 'Forbidden for non-admin-panel roles.' },
        },
      },
    },
    '/api/admin-branding': {
      get: {
        summary: 'Public admin branding settings',
        responses: {
          200: { description: 'Branding payload (logo, favicon, tagline).' },
        },
      },
    },
    '/api/auth/send-verification': {
      post: {
        summary: 'Send verification code/link to identifier',
        responses: {
          200: { description: 'Verification dispatched.' },
          400: { description: 'Validation error.' },
          429: { description: 'Rate limit exceeded.' },
        },
      },
    },
    '/api/auth/verify-phone': {
      post: {
        summary: 'Verify phone using OTP code',
        responses: {
          200: { description: 'Phone verified.' },
          400: { description: 'Invalid or expired code.' },
        },
      },
    },
    '/api/auth/verify-email': {
      post: {
        summary: 'Verify email using OTP code',
        responses: {
          200: { description: 'Email verified.' },
          400: { description: 'Invalid or expired code.' },
        },
      },
    },
    '/api/auth/verify-email/{token}': {
      get: {
        summary: 'Verify email using link token',
        parameters: [{ name: 'token', in: 'path', required: true, schema: { type: 'string' } }],
        responses: {
          200: { description: 'Email verified.' },
          400: { description: 'Invalid or expired token.' },
        },
      },
    },
    '/api/auth/admin/verify-identifier': {
      post: {
        summary: 'Admin verification helper for identifiers',
        responses: {
          200: { description: 'Verification state updated.' },
          400: { description: 'Validation error.' },
          403: { description: 'Forbidden.' },
        },
      },
    },
    '/api/discounts/coupons/{id}/usage': {
      get: {
        summary: 'Coupon usage analytics/details by coupon id',
        parameters: [{ name: 'id', in: 'path', required: true, schema: { type: 'string' } }],
        responses: {
          200: { description: 'Usage details.' },
          403: { description: 'Forbidden.' },
          404: { description: 'Coupon not found.' },
        },
      },
    },
  },
} as const

