/**
 * Supplemental OpenAPI contract for routes not currently emitted by payload-oapi.
 * This includes custom endpoints and known auth/verification routes.
 */
export const customEndpointsOpenApi = {
  openapi: '3.0.3',
  info: {
    title: 'BS-Commerce Supplemental API Endpoints',
    version: '1.0.0',
    description: 'Supplemental contract for routes missing from autogenerated Payload OpenAPI output.',
  },
  paths: {
    '/api/users/login': {
      post: {
        summary: 'Payload auth login (username/email + password)',
        responses: {
          200: { description: 'Authenticated.' },
          400: { description: 'Validation error.' },
          401: { description: 'Invalid credentials.' },
        },
      },
    },
    '/api/users/logout': {
      post: {
        summary: 'Payload auth logout',
        responses: {
          200: { description: 'Logged out.' },
          400: { description: 'Validation error.' },
          401: { description: 'Unauthorized.' },
        },
      },
    },
    '/api/users/me': {
      get: {
        summary: 'Current authenticated user profile',
        responses: {
          200: { description: 'Current user payload.' },
          401: { description: 'Unauthorized.' },
        },
      },
    },
    '/api/auth/login': {
      post: {
        summary: 'Login with email or phone identifier',
        requestBody: {
          required: true,
          content: {
            'application/json': {
              schema: {
                type: 'object',
                required: ['identifier', 'password'],
                properties: {
                  identifier: { type: 'string', description: 'Email or phone number.' },
                  password: { type: 'string' },
                },
              },
            },
          },
        },
        responses: {
          200: { description: 'Authenticated successfully.' },
          400: { description: 'Validation error.' },
          401: { description: 'Invalid credentials.' },
          403: { description: 'Verification gate blocked login.' },
        },
      },
    },
    '/api/guest/order-lookup': {
      post: {
        summary: 'Lookup guest order by reference and email/phone',
        responses: {
          200: { description: 'Order found.' },
          400: { description: 'Validation error.' },
          404: { description: 'Order not found.' },
        },
      },
    },
    '/api/checkout/process': {
      post: {
        summary: 'Process checkout payload into an order',
        responses: {
          200: { description: 'Checkout processed.' },
          400: { description: 'Invalid payload.' },
          401: { description: 'Unauthorized when required.' },
          409: { description: 'Inventory or business-rule conflict.' },
        },
      },
    },
    '/api/dashboard-stats': {
      get: {
        summary: 'Role-scoped admin dashboard metrics',
        responses: {
          200: { description: 'Stats response for admin or vendor role.' },
          401: { description: 'Unauthorized.' },
          403: { description: 'Forbidden for non-admin-panel roles.' },
        },
      },
    },
    '/api/admin-branding': {
      get: {
        summary: 'Public admin branding settings',
        responses: {
          200: { description: 'Branding payload (logo, favicon, tagline).' },
        },
      },
    },
    '/api/auth/send-verification': {
      post: {
        summary: 'Send verification code/link to identifier',
        responses: {
          200: { description: 'Verification dispatched.' },
          400: { description: 'Validation error.' },
          429: { description: 'Rate limit exceeded.' },
        },
      },
    },
    '/api/auth/verify-phone': {
      post: {
        summary: 'Verify phone using OTP code',
        responses: {
          200: { description: 'Phone verified.' },
          400: { description: 'Invalid or expired code.' },
        },
      },
    },
    '/api/auth/verify-email': {
      post: {
        summary: 'Verify email using OTP code',
        responses: {
          200: { description: 'Email verified.' },
          400: { description: 'Invalid or expired code.' },
        },
      },
    },
    '/api/auth/verify-email/{token}': {
      get: {
        summary: 'Verify email using link token',
        parameters: [{ name: 'token', in: 'path', required: true, schema: { type: 'string' } }],
        responses: {
          200: { description: 'Email verified.' },
          400: { description: 'Invalid or expired token.' },
        },
      },
    },
    '/api/auth/admin/verify-identifier': {
      post: {
        summary: 'Admin verification helper for identifiers',
        responses: {
          200: { description: 'Verification state updated.' },
          400: { description: 'Validation error.' },
          403: { description: 'Forbidden.' },
        },
      },
    },
    '/api/discounts/coupons/{id}/usage': {
      get: {
        summary: 'Coupon usage analytics/details by coupon id',
        parameters: [{ name: 'id', in: 'path', required: true, schema: { type: 'string' } }],
        responses: {
          200: { description: 'Usage details.' },
          403: { description: 'Forbidden.' },
          404: { description: 'Coupon not found.' },
        },
      },
    },
  },
} as const

