'use client'

import React, { useRef, useState, useEffect, useCallback } from 'react'
import { SetStepNav } from '@payloadcms/ui'
import type { ReportCategory, ReportType, ReportPeriod } from '../../../../lib/admin-reports'

export type ReportMetaDef = {
  key: ReportType
  label: string
  category: ReportCategory
  categoryLabel: string
  description: string
}

export type CategoryMeta = {
  key: ReportCategory
  title: string
  description: string
}

export const CATEGORY_DEFINITIONS: Record<ReportCategory, CategoryMeta> = {
  sales: {
    key: 'sales',
    title: 'Sales Analytics',
    description: 'Commercial sales volume, gross and net revenue, promo coupons, payment methods, and customer retention.',
  },
  products: {
    key: 'products',
    title: 'Product & Catalog',
    description: 'Product catalog performance, bestselling items, revenue distribution by category, and customer demand trends.',
  },
  customers: {
    key: 'customers',
    title: 'Customer Engagement',
    description: 'Customer behavior analytics, cart abandonment tracking, lifetime value (LTV), and top purchasing accounts.',
  },
  inventory: {
    key: 'inventory',
    title: 'Inventory & Operations',
    description: 'Multi-outlet stock valuation, threshold restock alerts, and inventory health across warehouses and store locations.',
  },
}

export const REPORT_DEFINITIONS: Record<ReportType, ReportMetaDef> = {
  'sales-overview': {
    key: 'sales-overview',
    label: 'Sales Overview & Revenue',
    category: 'sales',
    categoryLabel: 'Sales Analytics',
    description: 'Gross commercial sales, net revenue, total order volume, and average order value (AOV) over time.',
  },
  'sales-by-time': {
    key: 'sales-by-time',
    label: 'Sales by Day & Time',
    category: 'sales',
    categoryLabel: 'Sales Analytics',
    description: 'Order frequency and revenue patterns broken down across days of the week.',
  },
  'sales-by-payment': {
    key: 'sales-by-payment',
    label: 'Sales by Payment Method',
    category: 'sales',
    categoryLabel: 'Sales Analytics',
    description: 'Revenue distribution across payment methods (SSLCommerz, Cash on Delivery, Stripe).',
  },
  'sales-by-coupon': {
    key: 'sales-by-coupon',
    label: 'Sales by Coupon & Discount',
    category: 'sales',
    categoryLabel: 'Sales Analytics',
    description: 'Usage count, discounted amounts, and gross revenue generated by promo codes.',
  },
  'sales-by-geo': {
    key: 'sales-by-geo',
    label: 'Sales by Geographic Region',
    category: 'sales',
    categoryLabel: 'Sales Analytics',
    description: 'Commercial performance across shipping divisions, cities, and country regions.',
  },
  'new-vs-returning': {
    key: 'new-vs-returning',
    label: 'New vs. Returning Customers',
    category: 'sales',
    categoryLabel: 'Sales Analytics',
    description: 'First-time buyer acquisition vs repeat customer loyalty and revenue share.',
  },
  'product-performance': {
    key: 'product-performance',
    label: 'Product Performance & Bestsellers',
    category: 'products',
    categoryLabel: 'Product & Catalog',
    description: 'Top-selling SKUs by quantity sold, net revenue, and average selling price.',
  },
  'sales-by-category': {
    key: 'sales-by-category',
    label: 'Sales by Category',
    category: 'products',
    categoryLabel: 'Product & Catalog',
    description: 'Revenue and item volume breakdown across catalog categories.',
  },
  'product-demand': {
    key: 'product-demand',
    label: 'Product Demand & Wishlists',
    category: 'products',
    categoryLabel: 'Product & Catalog',
    description: 'Customer interest metrics, cart additions, and most wishlisted items.',
  },
  'abandoned-carts': {
    key: 'abandoned-carts',
    label: 'Abandoned Carts Overview',
    category: 'customers',
    categoryLabel: 'Customer Engagement',
    description: 'Uncompleted checkouts, cart abandonment rate, and recoverable pipeline value.',
  },
  'customer-ltv': {
    key: 'customer-ltv',
    label: 'Customer Lifetime Value (Top Spenders)',
    category: 'customers',
    categoryLabel: 'Customer Engagement',
    description: 'Highest spending customer accounts, total order counts, and historical spend.',
  },
  'abandoned-products': {
    key: 'abandoned-products',
    label: 'Most Abandoned Products',
    category: 'customers',
    categoryLabel: 'Customer Engagement',
    description: 'Products frequently added to cart but abandoned prior to payment completion.',
  },
  'customer-orders': {
    key: 'customer-orders',
    label: 'Customer Orders & Devices',
    category: 'customers',
    categoryLabel: 'Customer Engagement',
    description: 'Detailed customer purchase orders with client device type, browser, OS, and IP address intelligence.',
  },
  'low-stock-alert': {
    key: 'low-stock-alert',
    label: 'Low Stock & Restock Alerts',
    category: 'inventory',
    categoryLabel: 'Inventory & Operations',
    description: 'Inventory items at or below reorder thresholds needing replenishment.',
  },
  'stock-valuation': {
    key: 'stock-valuation',
    label: 'Stock Valuation by Store',
    category: 'inventory',
    categoryLabel: 'Inventory & Operations',
    description: 'Total on-hand inventory unit counts and cost/retail valuation by outlet.',
  },
}

export function CategoryIcon({ category, size = 20 }: { category: ReportCategory; size?: number }) {
  const props = {
    width: size,
    height: size,
    viewBox: '0 0 24 24',
    fill: 'none',
    stroke: 'currentColor',
    strokeWidth: '2',
    strokeLinecap: 'round' as const,
    strokeLinejoin: 'round' as const,
  }

  switch (category) {
    case 'sales':
      return (
        <svg {...props}>
          <line x1="18" y1="20" x2="18" y2="10" />
          <line x1="12" y1="20" x2="12" y2="4" />
          <line x1="6" y1="20" x2="6" y2="14" />
        </svg>
      )
    case 'products':
      return (
        <svg {...props}>
          <path d="M21 16V8a2 2 0 0 0-1-1.73l-7-4a2 2 0 0 0-2 0l-7 4A2 2 0 0 0 3 8v8a2 2 0 0 0 1 1.73l7 4a2 2 0 0 0 2 0l7-4A2 2 0 0 0 21 16z" />
          <polyline points="3.27 6.96 12 12.01 20.73 6.96" />
          <line x1="12" y1="22.08" x2="12" y2="12" />
        </svg>
      )
    case 'customers':
      return (
        <svg {...props}>
          <path d="M17 21v-2a4 4 0 0 0-4-4H5a4 4 0 0 0-4 4v2" />
          <circle cx="9" cy="7" r="4" />
          <path d="M23 21v-2a4 4 0 0 0-3-3.87" />
          <path d="M16 3.13a4 4 0 0 1 0 7.75" />
        </svg>
      )
    case 'inventory':
      return (
        <svg {...props}>
          <path d="M3 9l9-7 9 7v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z" />
          <polyline points="9 22 9 12 15 12 15 22" />
        </svg>
      )
    default:
      return (
        <svg {...props}>
          <line x1="18" y1="20" x2="18" y2="10" />
          <line x1="12" y1="20" x2="12" y2="4" />
          <line x1="6" y1="20" x2="6" y2="14" />
        </svg>
      )
  }
}

export function ReportIcon({ type, size = 15 }: { type: ReportType; size?: number }) {
  const props = {
    width: size,
    height: size,
    viewBox: '0 0 24 24',
    fill: 'none',
    stroke: 'currentColor',
    strokeWidth: '2',
    strokeLinecap: 'round' as const,
    strokeLinejoin: 'round' as const,
  }

  switch (type) {
    case 'sales-overview':
      return (
        <svg {...props}>
          <line x1="18" y1="20" x2="18" y2="10" />
          <line x1="12" y1="20" x2="12" y2="4" />
          <line x1="6" y1="20" x2="6" y2="14" />
        </svg>
      )
    case 'sales-by-time':
      return (
        <svg {...props}>
          <circle cx="12" cy="12" r="10" />
          <polyline points="12 6 12 12 16 14" />
        </svg>
      )
    case 'sales-by-payment':
      return (
        <svg {...props}>
          <rect x="1" y="4" width="22" height="16" rx="2" ry="2" />
          <line x1="1" y1="10" x2="23" y2="10" />
        </svg>
      )
    case 'sales-by-coupon':
      return (
        <svg {...props}>
          <path d="M20.59 13.41l-7.17 7.17a2 2 0 0 1-2.83 0L2 12V2h10l8.59 8.59a2 2 0 0 1 0 2.82z" />
          <line x1="7" y1="7" x2="7.01" y2="7" />
        </svg>
      )
    case 'sales-by-geo':
      return (
        <svg {...props}>
          <circle cx="12" cy="12" r="10" />
          <line x1="2" y1="12" x2="22" y2="12" />
          <path d="M12 2a15.3 15.3 0 0 1 4 10 15.3 15.3 0 0 1-4 10 15.3 15.3 0 0 1-4-10 15.3 15.3 0 0 1 4-10z" />
        </svg>
      )
    case 'new-vs-returning':
      return (
        <svg {...props}>
          <path d="M17 21v-2a4 4 0 0 0-4-4H5a4 4 0 0 0-4 4v2" />
          <circle cx="9" cy="7" r="4" />
          <path d="M23 21v-2a4 4 0 0 0-3-3.87" />
          <path d="M16 3.13a4 4 0 0 1 0 7.75" />
        </svg>
      )
    case 'product-performance':
      return (
        <svg {...props}>
          <path d="M21 16V8a2 2 0 0 0-1-1.73l-7-4a2 2 0 0 0-2 0l-7 4A2 2 0 0 0 3 8v8a2 2 0 0 0 1 1.73l7 4a2 2 0 0 0 2 0l7-4A2 2 0 0 0 21 16z" />
          <polyline points="3.27 6.96 12 12.01 20.73 6.96" />
          <line x1="12" y1="22.08" x2="12" y2="12" />
        </svg>
      )
    case 'sales-by-category':
      return (
        <svg {...props}>
          <path d="M22 19a2 2 0 0 1-2 2H4a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h5l2 3h9a2 2 0 0 1 2 2z" />
        </svg>
      )
    case 'product-demand':
      return (
        <svg {...props}>
          <polygon points="12 2 15.09 8.26 22 9.27 17 14.14 18.18 21.02 12 17.77 5.82 21.02 7 14.14 2 9.27 8.91 8.26 12 2" />
        </svg>
      )
    case 'abandoned-carts':
      return (
        <svg {...props}>
          <circle cx="9" cy="21" r="1" />
          <circle cx="20" cy="21" r="1" />
          <path d="M1 1h4l2.68 13.39a2 2 0 0 0 2 1.61h9.72a2 2 0 0 0 2-1.61L23 6H6" />
        </svg>
      )
    case 'customer-ltv':
      return (
        <svg {...props}>
          <path d="M20 21v-2a4 4 0 0 0-4-4H8a4 4 0 0 0-4 4v2" />
          <circle cx="12" cy="7" r="4" />
        </svg>
      )
    case 'abandoned-products':
      return (
        <svg {...props}>
          <path d="M6 2L3 6v14a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2V6l-3-4z" />
          <line x1="3" y1="6" x2="21" y2="6" />
          <path d="M16 10a4 4 0 0 1-8 0" />
        </svg>
      )
    case 'customer-orders':
      return (
        <svg {...props}>
          <rect x="2" y="3" width="20" height="14" rx="2" ry="2" />
          <line x1="8" y1="21" x2="16" y2="21" />
          <line x1="12" y1="17" x2="12" y2="21" />
        </svg>
      )
    case 'low-stock-alert':
      return (
        <svg {...props}>
          <path d="M10.29 3.86L1.82 18a2 2 0 0 0 1.71 3h16.94a2 2 0 0 0 1.71-3L13.71 3.86a2 2 0 0 0-3.42 0z" />
          <line x1="12" y1="9" x2="12" y2="13" />
          <line x1="12" y1="17" x2="12.01" y2="17" />
        </svg>
      )
    case 'stock-valuation':
      return (
        <svg {...props}>
          <path d="M3 9l9-7 9 7v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z" />
          <polyline points="9 22 9 12 15 12 15 22" />
        </svg>
      )
    default:
      return (
        <svg {...props}>
          <line x1="18" y1="20" x2="18" y2="10" />
          <line x1="12" y1="20" x2="12" y2="4" />
          <line x1="6" y1="20" x2="6" y2="14" />
        </svg>
      )
  }
}

function SubReportTabs({
  categoryReports,
  reportType,
  onReportTypeChange,
}: {
  categoryReports: ReportMetaDef[]
  reportType: ReportType
  onReportTypeChange: (type: ReportType) => void
}) {
  const containerRef = useRef<HTMLDivElement>(null)
  const activeTabRef = useRef<HTMLButtonElement>(null)
  const [canScrollLeft, setCanScrollLeft] = useState(false)
  const [canScrollRight, setCanScrollRight] = useState(false)

  const checkScroll = useCallback(() => {
    const el = containerRef.current
    if (!el) return
    const { scrollLeft, scrollWidth, clientWidth } = el
    setCanScrollLeft(scrollLeft > 4)
    setCanScrollRight(scrollLeft + clientWidth < scrollWidth - 4)
  }, [])

  useEffect(() => {
    checkScroll()
    const el = containerRef.current
    if (!el) return

    const handleResize = () => checkScroll()
    window.addEventListener('resize', handleResize)

    return () => {
      window.removeEventListener('resize', handleResize)
    }
  }, [checkScroll, categoryReports])

  // Auto-scroll active tab into view when selected
  useEffect(() => {
    if (activeTabRef.current) {
      activeTabRef.current.scrollIntoView({
        behavior: 'smooth',
        block: 'nearest',
        inline: 'center',
      })
    }
  }, [reportType])

  const scrollBy = (offset: number) => {
    if (containerRef.current) {
      containerRef.current.scrollBy({ left: offset, behavior: 'smooth' })
    }
  }

  if (categoryReports.length <= 1) return null

  return (
    <div
      style={{
        position: 'relative',
        display: 'flex',
        alignItems: 'center',
        background: 'var(--theme-elevation-100)',
        borderRadius: 8,
        border: '1px solid var(--theme-elevation-200)',
        padding: '3px',
      }}
    >
      {/* Scroll Left Button */}
      {canScrollLeft && (
        <button
          type="button"
          onClick={() => scrollBy(-220)}
          title="Scroll tabs left"
          style={{
            position: 'absolute',
            left: 4,
            zIndex: 4,
            width: 26,
            height: 26,
            borderRadius: 6,
            background: 'var(--theme-elevation-0, #fff)',
            border: '1px solid var(--theme-elevation-200)',
            color: 'var(--theme-text)',
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'center',
            cursor: 'pointer',
            boxShadow: '0 2px 4px rgba(0,0,0,0.12)',
            padding: 0,
          }}
        >
          <svg
            width="14"
            height="14"
            viewBox="0 0 24 24"
            fill="none"
            stroke="currentColor"
            strokeWidth="2.5"
            strokeLinecap="round"
            strokeLinejoin="round"
          >
            <polyline points="15 18 9 12 15 6" />
          </svg>
        </button>
      )}

      {/* Tabs list container */}
      <div
        ref={containerRef}
        onScroll={checkScroll}
        style={{
          display: 'flex',
          alignItems: 'center',
          gap: '0.35rem',
          overflowX: 'auto',
          WebkitOverflowScrolling: 'touch',
          scrollbarWidth: 'none',
          padding: '2px',
          width: '100%',
        }}
      >
        {categoryReports.map((r) => {
          const isActive = r.key === reportType
          return (
            <button
              key={r.key}
              ref={isActive ? activeTabRef : null}
              type="button"
              onClick={() => onReportTypeChange(r.key)}
              style={{
                display: 'inline-flex',
                alignItems: 'center',
                gap: 6,
                padding: '0.45rem 0.85rem',
                borderRadius: 6,
                border: 'none',
                background: isActive ? 'var(--theme-elevation-0, #fff)' : 'transparent',
                color: isActive ? 'var(--theme-text)' : 'var(--theme-elevation-600)',
                fontWeight: isActive ? 600 : 500,
                fontSize: 13,
                cursor: 'pointer',
                whiteSpace: 'nowrap',
                flexShrink: 0,
                boxShadow: isActive ? '0 1px 3px rgba(0,0,0,0.08)' : 'none',
                transition: 'all 0.15s ease',
              }}
            >
              <ReportIcon type={r.key} size={15} />
              <span>{r.label}</span>
            </button>
          )
        })}
      </div>

      {/* Scroll Right Button */}
      {canScrollRight && (
        <button
          type="button"
          onClick={() => scrollBy(220)}
          title="Scroll tabs right"
          style={{
            position: 'absolute',
            right: 4,
            zIndex: 4,
            width: 26,
            height: 26,
            borderRadius: 6,
            background: 'var(--theme-elevation-0, #fff)',
            border: '1px solid var(--theme-elevation-200)',
            color: 'var(--theme-text)',
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'center',
            cursor: 'pointer',
            boxShadow: '0 2px 4px rgba(0,0,0,0.12)',
            padding: 0,
          }}
        >
          <svg
            width="14"
            height="14"
            viewBox="0 0 24 24"
            fill="none"
            stroke="currentColor"
            strokeWidth="2.5"
            strokeLinecap="round"
            strokeLinejoin="round"
          >
            <polyline points="9 18 15 12 9 6" />
          </svg>
        </button>
      )}
    </div>
  )
}

type ReportHeaderProps = {
  category: ReportCategory
  reportType: ReportType
  period: ReportPeriod
  startDate: string
  endDate: string
  customStartDate: string
  customEndDate: string
  selectedStoreId: string | null
  availableStores: Array<{ id: string; name: string; code: string }>
  selectedCurrency?: string | null
  defaultCurrency?: string
  availableCurrencies?: string[]
  activeCurrency?: string
  loading: boolean
  onReportTypeChange: (type: ReportType) => void
  onPeriodChange: (period: ReportPeriod) => void
  onCustomDateChange: (start: string, end: string) => void
  onApplyCustomRange: () => void
  onStoreChange: (storeId: string | null) => void
  onCurrencyChange?: (currency: string | null) => void
  onRefresh: () => void
  onExportCsv: () => void
}

export function ReportHeader({
  category,
  reportType,
  period,
  startDate,
  endDate,
  customStartDate,
  customEndDate,
  selectedStoreId,
  availableStores,
  selectedCurrency,
  defaultCurrency,
  availableCurrencies,
  activeCurrency,
  loading,
  onReportTypeChange,
  onPeriodChange,
  onCustomDateChange,
  onApplyCustomRange,
  onStoreChange,
  onCurrencyChange,
  onRefresh,
  onExportCsv,
}: ReportHeaderProps) {
  const currentDef = REPORT_DEFINITIONS[reportType] || REPORT_DEFINITIONS['sales-overview']
  const categoryMeta = CATEGORY_DEFINITIONS[category] || CATEGORY_DEFINITIONS['sales']
  const isCustom = period === 'custom'

  // Reports belonging to the current category
  const categoryReports = Object.values(REPORT_DEFINITIONS).filter((r) => r.category === category)

  const inputStyle: React.CSSProperties = {
    padding: '0.45rem 0.75rem',
    borderRadius: 6,
    border: '1px solid var(--theme-elevation-200)',
    background: 'var(--theme-elevation-0, #fff)',
    color: 'var(--theme-text)',
    fontSize: 13,
    fontWeight: 500,
    outline: 'none',
    cursor: 'pointer',
    fontFamily: 'inherit',
    height: 34,
    boxSizing: 'border-box',
  }

  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: '1.25rem', marginBottom: '1.5rem' }}>
      {/* 1. Global Admin Top Bar StepNav Integration (Steady category title across tabs) */}
      <SetStepNav
        nav={[
          {
            label: 'Reports & Analytics',
            url: '/admin/reports',
          },
          {
            label: categoryMeta.title,
          },
        ]}
      />

      {/* 2. Steady Category Header & Global Actions */}
      <div
        style={{
          display: 'flex',
          flexWrap: 'wrap',
          justifyContent: 'space-between',
          alignItems: 'center',
          gap: '1rem',
        }}
      >
        <div style={{ minWidth: 0 }}>
          <div style={{ display: 'flex', alignItems: 'center', gap: 8, flexWrap: 'wrap' }}>
            <h1 style={{ fontSize: 22, fontWeight: 700, margin: 0, color: 'var(--theme-text)' }}>
                {categoryMeta.title}
              </h1>
              <span
                style={{
                  fontSize: 11,
                  fontWeight: 600,
                  textTransform: 'uppercase',
                  letterSpacing: '0.04em',
                  padding: '2px 8px',
                  borderRadius: 4,
                  background: 'var(--theme-elevation-150)',
                  color: 'var(--theme-elevation-600)',
                }}
              >
                Reports
              </span>
            </div>
            <p
              style={{
                color: 'var(--theme-elevation-500)',
                fontSize: 13,
                marginTop: 4,
                marginBottom: 0,
                lineHeight: 1.4,
              }}
            >
              {categoryMeta.description}
            </p>
          </div>

        {/* Global Currency & Store Filters & Action Buttons */}
        <div style={{ display: 'flex', alignItems: 'center', gap: '0.65rem', flexWrap: 'wrap' }}>
          {availableCurrencies && availableCurrencies.length > 0 && onCurrencyChange && (
            <select
              value={selectedCurrency || ''}
              onChange={(e) => onCurrencyChange(e.target.value ? e.target.value : null)}
              style={inputStyle}
              title="Select currency for reports and analytics"
            >
              <option value="">Currency: {defaultCurrency || 'USD'} (Default)</option>
              {availableCurrencies.map((c) => (
                <option key={c} value={c}>
                  Currency: {c} ({c === 'BDT' ? '৳' : c === 'USD' ? '$' : c})
                </option>
              ))}
            </select>
          )}

          {availableStores.length > 0 && (
            <select
              value={selectedStoreId || ''}
              onChange={(e) => onStoreChange(e.target.value ? e.target.value : null)}
              style={inputStyle}
              title="Filter by outlet"
            >
              <option value="">All Outlets / Stores</option>
              {availableStores.map((s) => (
                <option key={s.id} value={s.id}>
                  {s.name}
                </option>
              ))}
            </select>
          )}

          <button
            type="button"
            onClick={onRefresh}
            disabled={loading}
            title="Refresh Data"
            style={{
              ...inputStyle,
              display: 'inline-flex',
              alignItems: 'center',
              gap: 6,
              background: 'var(--theme-elevation-100)',
              cursor: loading ? 'not-allowed' : 'pointer',
              opacity: loading ? 0.6 : 1,
            }}
          >
            <svg
              width="13"
              height="13"
              viewBox="0 0 24 24"
              fill="none"
              stroke="currentColor"
              strokeWidth="2.2"
              strokeLinecap="round"
              strokeLinejoin="round"
              style={{
                animation: loading ? 'spin 1s linear infinite' : 'none',
              }}
            >
              <path d="M21.5 2v6h-6M21.34 15.57a10 10 0 1 1-.57-8.38l5.67-5.67" />
            </svg>
            <span>{loading ? 'Refreshing…' : 'Refresh'}</span>
          </button>

          <button
            type="button"
            onClick={onExportCsv}
            title="Export data as CSV"
            style={{
              ...inputStyle,
              background: 'var(--theme-elevation-100)',
              color: 'var(--theme-text)',
              display: 'inline-flex',
              alignItems: 'center',
              gap: 6,
            }}
          >
            <svg
              width="13"
              height="13"
              viewBox="0 0 24 24"
              fill="none"
              stroke="currentColor"
              strokeWidth="2"
              strokeLinecap="round"
              strokeLinejoin="round"
            >
              <path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4" />
              <polyline points="7 10 12 15 17 10" />
              <line x1="12" y1="15" x2="12" y2="3" />
            </svg>
            <span>Export CSV</span>
          </button>
        </div>
      </div>

      {/* 3. Sub-Report Tabs with Scroll Navigation and Auto-Centering */}
      <SubReportTabs
        categoryReports={categoryReports}
        reportType={reportType}
        onReportTypeChange={onReportTypeChange}
      />

      {/* 4. Active Sub-Report Description & Time Filter Toolbar */}
      <div
        style={{
          display: 'flex',
          flexDirection: 'column',
          gap: '0.85rem',
          padding: '0.85rem 1.15rem',
          borderRadius: 8,
          background: 'var(--theme-elevation-50)',
          border: '1px solid var(--theme-elevation-200)',
        }}
      >
        {/* Active Report Title & Description */}
        <div
          style={{
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'space-between',
            flexWrap: 'wrap',
            gap: '0.5rem',
            paddingBottom: '0.75rem',
            borderBottom: '1px solid var(--theme-elevation-150)',
          }}
        >
          <div style={{ display: 'flex', alignItems: 'center', gap: 8, flexWrap: 'wrap' }}>
            <span style={{ fontSize: 14, fontWeight: 700, color: 'var(--theme-text)' }}>
              {currentDef.label}
            </span>
            <span style={{ color: 'var(--theme-elevation-300)' }}>•</span>
            <span style={{ fontSize: 13, color: 'var(--theme-elevation-500)' }}>
              {currentDef.description}
            </span>
          </div>

          {startDate && endDate && (
            <div style={{ display: 'flex', alignItems: 'center', gap: 10, fontSize: 12, color: 'var(--theme-elevation-500)', whiteSpace: 'nowrap', flexWrap: 'wrap' }}>
              {activeCurrency && (
                <span
                  style={{
                    padding: '2px 8px',
                    borderRadius: 4,
                    background: 'var(--theme-elevation-150)',
                    color: 'var(--theme-text)',
                    fontWeight: 600,
                    fontSize: 11,
                    textTransform: 'uppercase',
                    letterSpacing: '0.04em',
                  }}
                  title={`Active reporting currency: ${activeCurrency}`}
                >
                  Currency: {activeCurrency} ({activeCurrency === 'BDT' ? '৳' : activeCurrency === 'USD' ? '$' : activeCurrency})
                </span>
              )}
              <div>
                <span>Period: </span>
                <strong style={{ color: 'var(--theme-text)', fontWeight: 600 }}>
                  {new Date(startDate).toLocaleDateString(undefined, {
                    month: 'short',
                    day: 'numeric',
                    year: 'numeric',
                  })}{' '}
                  –{' '}
                  {new Date(endDate).toLocaleDateString(undefined, {
                    month: 'short',
                    day: 'numeric',
                    year: 'numeric',
                  })}
                </strong>
              </div>
            </div>
          )}
        </div>

        {/* Time Period Filter Pills */}
        <div
          style={{
            display: 'flex',
            flexWrap: 'wrap',
            alignItems: 'center',
            justifyContent: 'space-between',
            gap: '0.75rem',
          }}
        >
          <div style={{ display: 'flex', alignItems: 'center', gap: '0.4rem', flexWrap: 'wrap' }}>
            <span
              style={{
                fontSize: 11,
                fontWeight: 600,
                textTransform: 'uppercase',
                letterSpacing: '0.04em',
                color: 'var(--theme-elevation-500)',
                marginRight: 4,
              }}
            >
              Time Filter:
            </span>
            {(['day', 'week', 'month', 'quarter', 'year', 'custom'] as ReportPeriod[]).map((p) => (
              <button
                key={p}
                type="button"
                onClick={() => onPeriodChange(p)}
                style={{
                  padding: '0.35rem 0.75rem',
                  borderRadius: 6,
                  fontSize: 12,
                  fontWeight: period === p ? 600 : 500,
                  border: '1px solid',
                  borderColor: period === p ? 'var(--theme-elevation-400)' : 'var(--theme-elevation-200)',
                  background: period === p ? 'var(--theme-elevation-150)' : 'var(--theme-elevation-0, #fff)',
                  color: period === p ? 'var(--theme-text)' : 'var(--theme-elevation-600)',
                  cursor: 'pointer',
                  transition: 'all 0.15s ease',
                }}
              >
                {p.charAt(0).toUpperCase() + p.slice(1)}
              </button>
            ))}
          </div>
        </div>

        {/* Custom Date Range Inputs (if custom is selected) */}
        {isCustom && (
          <div
            style={{
              display: 'flex',
              flexWrap: 'wrap',
              alignItems: 'center',
              gap: '0.75rem',
              paddingTop: '0.5rem',
              borderTop: '1px dashed var(--theme-elevation-200)',
            }}
          >
            <div style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
              <span style={{ fontSize: 12, fontWeight: 600, color: 'var(--theme-text)' }}>From:</span>
              <input
                type="date"
                value={customStartDate}
                onChange={(e) => onCustomDateChange(e.target.value, customEndDate)}
                style={inputStyle}
              />
            </div>
            <div style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
              <span style={{ fontSize: 12, fontWeight: 600, color: 'var(--theme-text)' }}>To:</span>
              <input
                type="date"
                value={customEndDate}
                onChange={(e) => onCustomDateChange(customStartDate, e.target.value)}
                style={inputStyle}
              />
            </div>
            <button
              type="button"
              onClick={onApplyCustomRange}
              style={{
                ...inputStyle,
                background: 'var(--theme-elevation-800, #1e293b)',
                color: '#ffffff',
                fontWeight: 600,
                padding: '0 1rem',
              }}
            >
              Apply Range
            </button>
          </div>
        )}
      </div>
    </div>
  )
}
